openapi: 3.0.1
info:
  title: AIchiever Plugin
  description: A plugin that allows the user to manage tasks using ChatGPT.
  version: "v1"
servers:
  - url: http://localhost:3000
paths:
  /tasks:
    post:
      operationId: addTask
      summary: Add a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
      responses:
        "200":
          description: OK
    get:
      operationId: getTasks
      summary: Get the list of tasks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      type: string
   /tasks/{taskId}:
    put:
      operationId: editTask
      summary: Edit an existing task
      parameters:
        - in: path
          name: taskId
          schema:
            type: integer
          required: true
          description: The ID of the task to edit.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
      responses:
        "200":
          description: OK
